package Classes;

import javax.swing.JOptionPane;

public class Main {
	public static void main(String[] args) {
		// TODO Autogenerated method stub
		
	}
	
	public Pessoa cadastrarPessoa() {
		int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o Id"));
		String nome = JOptionPane.showInputDialog("Digite o nome da pessoa");
		String endereco = JOptionPane.showInputDialog("Digite o endereco");
		boolean ativo = true;
		return null;
		
		Pessoa pessoa = new Pessoa(nome, endereco, etc);
				
				//ctrl+3 gcuf
	}

}
